services:
  postgres:
    image: postgres:16-alpine
    container_name: turnos_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: turnos
      POSTGRES_PASSWORD: turnos
      POSTGRES_DB: turnos
    ports:
      - "5434:5432"
    volumes:
      - turnos_pg_data:/var/lib/postgresql/data

volumes:
  turnos_pg_data:
